services:
  postgres:
    container_name: service_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=service_db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    ports:
      - 58441:5432
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_DEFAULT_USER=admin
    ports:
      - 5672
